# Generated by Django 2.1.7 on 2019-02-28 17:55

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='def_image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
