# Generated by Django 2.1.7 on 2019-02-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190228_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='def_image',
        ),
    ]
